In [1]:
import numpy as np

In [2]:
q_table = np.random.randint(-10, 10, size=(4, 3))

In [3]:
q_table

array([[ -2,   8,  -1],
       [  8,   5,  -8],
       [ -9,  -1,   1],
       [-10,   2,   4]])

In [6]:
np.multiply(q_table, q_table)

array([[  4,  64,   1],
       [ 64,  25,  64],
       [ 81,   1,   1],
       [100,   4,  16]])

In [6]:
players_turn = np.array([1, -1, 1, -1])

In [10]:
q_table

array([[-2,  1,  8],
       [-9, 10, -3],
       [ 3, -6,  4],
       [-2,  4,  9]])