In [1]:
import numpy as np
from functools import reduce

In [2]:
markers = np.array([[-1, -1, -1], [-1, -1, -1], [-1, -1, -1]])

markers[markers == -1] = 2
reduce(lambda acc, curr: acc * 3 + curr, markers.flatten())

19682

In [3]:
3 ** 9

19683

In [4]:
markers[(0, 0)]

2

In [2]:
def index_to_state(index: int) -> np.ndarray:
        """A utility function to convert index to state
        Args:
            index (int): index of the state from the state space

        Returns:
            np.ndarray: the current state of the board
        """
        board_size = 3
        state = np.zeros((board_size, board_size))
        for i in range(board_size):
            for j in range(board_size):
                state[i][j] = index % 3
                index = index // 3
        state[state == 2] = -1
        return state

In [3]:
val = index_to_state(7734)

In [4]:
val

array([[ 0.,  1.,  1.],
       [ 1., -1.,  1.],
       [ 1.,  0.,  1.]])

In [9]:
np.sum(np.diag(val, ))

0.0

In [7]:
int("101121110", base=3)

7734

In [8]:
transition_matrix = np.zeros((4, 4), dtype=np.float32)

In [9]:
transition_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [10]:
transition_matrix[2, 1] = 10
transition_matrix[2, 3] = 50

In [11]:
# transition_matrix[2] /= transition_matrix[2].sum()

In [15]:
transition_matrix

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0., 10.,  0., 50.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [16]:
transition_matrix[2] /= transition_matrix[2].sum()

In [17]:
transition_matrix[2].sum()

1.0

In [18]:
np.argwhere(transition_matrix[2] > 0)

array([[1],
       [3]], dtype=int64)

In [3]:
foo = [(0, 0)] * 3 ** 2
foo[1] = (1, 1)

In [4]:
foo

[(0, 0), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0)]

In [6]:
np.array(foo)

array([[0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])