In [1]:
import numpy as np
import cProfile
import pstats

In [11]:
def my_func(a):
    print(a)
    return a

In [13]:
# given a state and an action, how to get the next state efficiently

state_to_next = {i: i + 1 for i in range(1000000)}
with cProfile.Profile() as pr:
    res = np.apply_along_axis(my_func, -1, np.random.randint(0, 10, 10))

print(res)
ps = pstats.Stats(pr)
ps.sort_stats('cumtime').print_stats(10)

[4 4 3 9 8 7 5 9 8 2]
[4 4 3 9 8 7 5 9 8 2]
         255 function calls (237 primitive calls) in 0.001 seconds

   Ordered by: cumulative time
   List reduced from 93 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      9/2    0.000    0.000    0.001    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
        1    0.000    0.000    0.001    0.001 <__array_function__ internals>:177(apply_along_axis)
        1    0.000    0.000    0.001    0.001 e:\semester_8\RLA\env\lib\site-packages\numpy\lib\shape_base.py:267(apply_along_axis)
        1    0.000    0.000    0.001    0.001 C:\Users\Kranthi Sedamaki\AppData\Local\Temp\ipykernel_13904\3349019748.py:1(my_func)
        1    0.000    0.000    0.001    0.001 {built-in method builtins.print}
        2    0.000    0.000    0.000    0.000 e:\semester_8\RLA\env\lib\site-packages\ipykernel\iostream.py:535(write)
        2    0.000    0.000    0.000    0.000 e:\se

In [35]:
x = np.arange(10).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
def f(x):
    return str(x)

In [37]:
f(x)

'[[0 1 2 3 4]\n [5 6 7 8 9]]'

In [22]:
all_states = np.arange(1000000)

In [30]:
actions = np.random.randint(0, 3, (10, 2))

In [32]:
def get_next_state(state, action):
    x, y = action
    state[x][y] = state[x][y] + 1
    return state